import { RowDataPacket } from "mysql2";
import type { NextApiRequest, NextApiResponse } from "next";
import { PDFDocument, PDFFont, StandardFonts, rgb } from "pdf-lib";

import { pool } from "lib/database";
import { withSuperAdmin } from "@/lib/withSuperAdmin";
import { ROLE_BEHAVIORAL_STANDARDS_ID } from "@/constants";

// Port of the legacy VCcensus label sheet (censusprintsched.php userSched()).
// Prints one 2"x4" label per volunteer — schedule + passcode — onto Avery 5523
// stock (10-up, 2 cols x 5 rows on Letter). Geometry and font metrics were
// measured from a PDF generated by the legacy page so the output matches what
// has printed correctly on this stock for years.
//
// Add ?X=X to mask passcodes (legacy parity).

// "Passed online RS-test-out" (op_roles 1000011) has no constants.ts entry;
// 1000012 is ROLE_BEHAVIORAL_STANDARDS_ID ("Signed Behavioral Standards").
const ROLE_RS_TEST_OUT_ID = 1000011;

// Avery 5523: labels are 4in x 2in; rows start 0.5in from the page top with a
// 2in vertical pitch. Column x-origins and per-element baseline offsets below
// are the legacy PDF's measured text positions (points, PDF origin bottom-left).
const PAGE_W = 612;
const PAGE_H = 792;
const ROW_TOP0 = PAGE_H - 36; // top edge of label row 1
const ROW_PITCH = 144;
const COL_X = [44.64, 315.56];
const TABLE_W = 265.3; // content width used for centered lines

const RED = rgb(1, 0, 0);
const GREEN = rgb(0, 0.5, 0);
const BLACK = rgb(0, 0, 0);

interface VolunteerRow extends RowDataPacket {
  shiftboard_id: number;
  playa_name: string | null;
  world_name: string | null;
  passcode: string | null;
  bs: number;
  rs: number;
}
interface ShiftRow extends RowDataPacket {
  shiftboard_id: number;
  wd: string;
  dom: number;
  start_time_text: string | null;
  end_time_text: string | null;
  position: string | null;
}

const ordinal = (n: number) => {
  if (n % 100 >= 11 && n % 100 <= 13) return "th";
  return ["th", "st", "nd", "rd"][n % 10] ?? "th";
};

// legacy: str_replace over the position name, then 21-char cap
const positionText = (position: string | null) =>
  (position ?? "")
    .replaceAll("Pre Event ", "")
    .replaceAll("Census ", "")
    .replaceAll(" 5 SAP", "")
    .slice(0, 21);

const lastNameOf = (worldName: string | null) => {
  const parts = (worldName ?? "").trim().split(/\s+/).filter(Boolean);
  return parts.length ? parts[parts.length - 1] : "";
};

const labels = async (req: NextApiRequest, res: NextApiResponse) => {
  if (req.method !== "GET") {
    return res.status(405).json({ statusCode: 405, message: "Method not allowed" });
  }
  const mask = req.query.X === "X";

  const [volunteerList] = await pool.query<VolunteerRow[]>(
    `SELECT
      v.shiftboard_id,
      v.playa_name,
      v.world_name,
      v.passcode,
      MAX(CASE WHEN vr.role_id = ? THEN 1 ELSE 0 END) AS bs,
      MAX(CASE WHEN vr.role_id = ? THEN 1 ELSE 0 END) AS rs
    FROM op_volunteers AS v
    LEFT JOIN op_volunteer_roles AS vr
      ON vr.shiftboard_id=v.shiftboard_id AND vr.remove_role=false
    WHERE v.delete_volunteer=false AND v.shiftboard_id > 1
    GROUP BY v.shiftboard_id, v.playa_name, v.world_name, v.passcode`,
    [ROLE_BEHAVIORAL_STANDARDS_ID, ROLE_RS_TEST_OUT_ID]
  );

  // legacy cutoff: shifts starting after midnight of PreWed (build-week
  // Wednesday) make the label; earlier pre-event shifts do not.
  const [shiftList] = await pool.query<ShiftRow[]>(
    `SELECT
      vs.shiftboard_id,
      DATE_FORMAT(d.date, '%a') AS wd,
      DAYOFMONTH(d.date) AS dom,
      st.start_time_text,
      st.end_time_text,
      COALESCE(NULLIF(stp.position_alias, ''), pt.position) AS position
    FROM op_volunteer_shifts AS vs
    JOIN op_shift_time_position AS stp ON stp.time_position_id=vs.time_position_id
    JOIN op_position_type AS pt ON pt.position_type_id=stp.position_type_id
    JOIN op_shift_times AS st ON st.shift_times_id=stp.shift_times_id
    JOIN op_dates AS d ON d.date_id=st.start_date_id
    JOIN (
      SELECT date FROM op_dates WHERE datename='PreWed' AND delete_date=false LIMIT 1
    ) AS pw ON d.date >= pw.date
    WHERE vs.remove_shift=false AND st.canceled=false
    ORDER BY vs.shiftboard_id, st.start_time`
  );

  const shiftsById = new Map<number, ShiftRow[]>();
  for (const row of shiftList) {
    const list = shiftsById.get(row.shiftboard_id) ?? [];
    list.push(row);
    shiftsById.set(row.shiftboard_id, list);
  }

  // legacy sort: volunteers without a last name first (by playa name), then by
  // last name + playa name, byte order
  const sorted = [...volunteerList]
    .map((v) => {
      const last = lastNameOf(v.world_name);
      const playa = v.playa_name ?? "";
      return { key: (last === "" ? "A" : `Z${last}`) + playa, last, playa, v };
    })
    .sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));

  const doc = await PDFDocument.create();
  doc.setTitle("Census Shifts");
  const helv = await doc.embedFont(StandardFonts.Helvetica);
  const helvBold = await doc.embedFont(StandardFonts.HelveticaBold);
  const helvItal = await doc.embedFont(StandardFonts.HelveticaOblique);
  const zapf = await doc.embedFont(StandardFonts.ZapfDingbats);

  const now = new Date();
  const printedAt = `Printed at ${now.toLocaleString("en-US", { month: "short" })} ${now.getDate()}${ordinal(now.getDate())} ${((now.getHours() + 11) % 12) + 1}${now.getHours() < 12 ? "am" : "pm"}`;

  let page = doc.addPage([PAGE_W, PAGE_H]);
  const centered = (
    text: string,
    x0: number,
    y: number,
    size: number,
    font: PDFFont,
  ) => {
    const w = font.widthOfTextAtSize(text, size);
    page.drawText(text, { x: x0 + (TABLE_W - w) / 2, y, size, font, color: BLACK });
  };

  sorted.forEach(({ last, playa, v }, i) => {
    const slot = i % 10;
    if (i > 0 && slot === 0) page = doc.addPage([PAGE_W, PAGE_H]);
    const x0 = COL_X[slot % 2];
    const top = ROW_TOP0 - Math.floor(slot / 2) * ROW_PITCH;

    // header: optional red dot (BS unsigned) + green star (RS test-out passed),
    // playa name, italic last name when the playa name doesn't contain it
    let x = x0 - 13.45;
    const nameY = top - 17.3;
    if (!v.bs) {
      page.drawText("●", { x, y: top - 20.2, size: 11, font: zapf, color: RED });
      x += zapf.widthOfTextAtSize("●", 11);
    }
    if (v.rs) {
      page.drawText("★", { x, y: top - 20.2, size: 11, font: zapf, color: GREEN });
      x += zapf.widthOfTextAtSize("★", 11);
    }
    const name = ` ${playa.slice(0, 20)}`;
    page.drawText(name, { x, y: nameY, size: 11, font: helv, color: BLACK });
    if (last !== "" && !playa.includes(last)) {
      x += helv.widthOfTextAtSize(name, 11);
      // keep the name clear of the passcode label (legacy wrapped instead,
      // which broke the label row layout)
      let lastText = ` ${last.slice(-18)}`;
      while (
        lastText.length > 2 &&
        x + helvItal.widthOfTextAtSize(lastText, 11) > x0 + 155
      ) {
        lastText = lastText.slice(0, -1);
      }
      page.drawText(lastText, { x, y: nameY, size: 11, font: helvItal, color: BLACK });
    }

    // passcode, label reversed so a casual glance doesn't read it
    const passcode = mask ? "xxxx" : (v.passcode ?? "").padEnd(4, "0");
    page.drawText("terceS susneC:", { x: x0 + 159.15, y: top - 15.3, size: 9, font: helv, color: BLACK });
    page.drawText(passcode, { x: x0 + 220.68, y: top - 15.3, size: 9, font: helvBold, color: BLACK });

    centered("Online survey: census.burningman.org", x0, top - 27.1, 7, helv);

    // schedule rows: <=7 shifts print at 9pt; 8-9 print all at 8pt; 10+ are
    // capped at 7 rows with an overflow note (legacy thresholds, including its
    // "total - 8" count)
    const shifts = shiftsById.get(v.shiftboard_id) ?? [];
    const dense = shifts.length > 7;
    const shown = shifts.length >= 10 ? shifts.slice(0, 7) : shifts;
    const size = dense ? 8 : 9;
    const [timeX, posX] = dense ? [42.45, 122.04] : [53.05, 145.89];
    const pitch = dense ? 10 : 11.25;
    let y = top - (dense ? 42.5 : 43.5);
    for (const s of shown) {
      page.drawText(`${s.wd} ${s.dom}${ordinal(s.dom)}`, { x: x0, y, size, font: helv, color: BLACK });
      page.drawText(`${s.start_time_text ?? ""} - ${s.end_time_text ?? ""}`, { x: x0 + timeX, y, size, font: helv, color: BLACK });
      page.drawText(positionText(s.position), { x: x0 + posX, y, size, font: helv, color: BLACK });
      y -= pitch;
    }
    y += pitch; // back to the last drawn line
    if (shifts.length > shown.length) {
      y -= pitch;
      centered(`****You have ${shifts.length - 8} more shifts not listed.****`, x0, y, 8, helv);
    }
    if (shown.length === 0) y = top - 27.1;
    centered(shifts.length > 0 ? printedAt : "New On Playa Volunteer", x0, y - 9.3, 7, helv);
  });

  const bytes = await doc.save();
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", 'inline; filename="CensusShifts.pdf"');
  return res.send(Buffer.from(bytes));
};

export default withSuperAdmin(labels);
